### ISSUE TITLE
[JOSS] LICENSE and DISCLAIMER

### ISSUE THREAD

**Issue by euronion** [IMMM-SFA/tell#31]
The repository contains a LICENSE and DISCLAIMER file which seem to be partially overlapping.

Is the DISCLAIMER obsolete or is it intended to extend the LICENSE file? I'm not a legal expert, but in the latter case i presume the LICENSE would no longer be BSD-2 but a modified one.

Can you check the DISCLAIMER file against the LICENSE and remove it if obsolete?

xref https://github.com/openjournals/joss-reviews/issues/4472

**Comment by mcgrathc** [comment]
The license and disclaimer are both required by our institution (PNNL) as part of their open-source software protocols. We cannot modify them. We’ve used this combination in other software packages (e.g., [CERF](https://github.com/IMMM-SFA/cerf)) that have gone through review and have been previously published in JOSS.

**Comment by mcgrathc** [comment]
Closing for now in agreement that the disclaimer and license of the software under consideration are ok for the publication in JOSS. Will open again if needed
