### ISSUE TITLE
[JOSS] Question regarding paper authors

### ISSUE THREAD

**Issue by euronion** [IMMM-SFA/tell#32]
This question relates to the paper authors:

The list include 9 people, whereas contributions to this repository have been made by only 5 of them.
As such it is not obvious to me whether all authors fulfill the [authorship criteria](https://joss.readthedocs.io/en/latest/submitting.html#authorship) by JOSS.

Maybe you can briefly state the type of involvement of the other authors in the software?

xref https://github.com/openjournals/joss-reviews/issues/4472

**Comment by mcgrathc** [comment]
@euronion, there are 5 authors that have made direct contributions to the repository: 

- Casey R. McGrath
- Casey D. Burleyson 
- Aowabin Rahman 
- Travis Thurber 
- Chris R. Vernon

There are 3 authors that did not directly contribute to the repository, but were critical in developing this software: 

- Jennie S. Rice: Substantial contributions to the conception and development of the software. Significantly contributed to paper revisions. Final approval of the version to be published. 
- Nathalie Voisin:  Substantial contributions to the development of the software. Provided interpretation of model results. Significantly contributed to paper revisions. 
- Zarrar Khan: Substantial contributions to the development of the software. Provided critical feedback when making decisions on model inputs. 

This adds to 8 authors in total, which we believe all made significant scholarly contributions to the software.

**Comment by euronion** [comment]
Thanks for the clarification!
