### ISSUE TITLE
[JOSS] Expand installation instructions

### ISSUE THREAD

**Issue by euronion** [IMMM-SFA/tell#33]
The installation instructions here:
*  https://immm-sfa.github.io/tell/README.html#install-tell
* https://immm-sfa.github.io/tell/tell_quickstarter.html#install-tell

are a bit meager. Consider adding some short comments with the following information:

* It is a Python package which requires a Python and pip installed
* Which Python versions are supported
* Whether there are platform limitations (Windows, Linux, MacOS) or whether the software has been tested to work on all plattforms

Installation did work for me (WSL2 on Windows 10 with Python=3.10.5) without problems.

xref: https://github.com/openjournals/joss-reviews/issues/4472

**Comment by mcgrathc** [comment]
The following was added to the installation instructions in the README and quick-starter: 

``tell` is available via GitHub repository by using the pip install functionality. `tell` requires a Python version between 3.8 and 4.0 as well as a pip install to import the package. `tell` has been tested on
Windows and Mac platforms.` 

The changes can be found in this PR: https://github.com/IMMM-SFA/tell/pull/41
