### ISSUE TITLE
[JOSS] Low test code coverage

### ISSUE THREAD

**Issue by euronion** [IMMM-SFA/tell#35]
The test coverage for the code is low (~31.40% according to CodeCov): https://app.codecov.io/gh/IMMM-SFA/tell ).

You might want to consider expanding the test coverage and include some more in-detail testing than e.g. the high level functionality tests in [`test_mlp_predict.py`](https://github.com/IMMM-SFA/tell/blob/main/tell/tests/test_mlp_predict.py).

xref https://github.com/openjournals/joss-reviews/issues/4472

**Comment by mcgrathc** [comment]
We have increased code coverage via specifically for the MLP testing in `test_mlp_utils.py`

**Comment by mcgrathc** [comment]
Closing if no further comments. Will reopen if needed.
