### ISSUE TITLE
[JOSS] Contact/Help and Contribution Guidelines

### ISSUE THREAD

**Issue by euronion** [IMMM-SFA/tell#38]
**Contact/Help**

Does the option for users to contact you or a mailinglist / tag in popular social media exists, which users with questions can use?
Or should users with questions open Issues on GitHub?

*Whatever preferred option you have should be included in the documentation.*

**Contribution Guidelines**
For good contributions and bug reports I suggest you specify which information users should include when they open Issues for Bug Reports or Features Requests (similar to what you have specified for Pull Requests in the Contribution Guidelines). Alternatively or in addition you can use GitHub templates for Issues and PRs ([example](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)).

**Comment by mcgrathc** [comment]
Contact help has been added to the README documentation: https://github.com/IMMM-SFA/tell/blob/main/README.md. Contribution Guidelines have been added for bug/feature reports in this PR for contributing.rst: https://github.com/IMMM-SFA/tell/pull/41. GitHub templates for Issues and PRs were also added.
